Review.destroy_all 
Item.destroy_all
Restaurant.destroy_all


puts "seeding reviews"

rev1 = Review.create(review:"its good, but ive had better honestly. They should put more effort into their customer service, tbh.", restaurant_id: 1, username: "Jake_the_man", dateposted: "01/20/2020", rating: 3)
rev2 = Review.create(review:"its ok, I guess...", restaurant_id: 2, username: "ZelieBellie", dateposted: "12/24/2016", rating: 2)
rev3 = Review.create(review:"its bad- they wouldnt serve me or feed me. Since when are you not supposed to be treated like royalty at a fastfood restaurant?? Pshhh, Americans.", restaurant_id: 3, username: "SamTheMan", dateposted: "09/02/2012", rating: 1)
rev4 = Review.create(review:"its alright, I wouldn't come back unless it was just super convenient or something.", restaurant_id: 4, username: "Anonymous", dateposted: "04/24/2012", rating: 4)
rev5 = Review.create(review:"celebrated my birthday here... would not come back. My husband forced me to come here and I think it's because he wanted to see the loose waitress that gives everyone too much attention.. I dunno, food was ok though.", restaurant_id: 5, username: "Anonymous", dateposted: "05/23/2016", rating: 5)
rev6 = Review.create(review:"its bomb, I had the cheapest thing on the menu but man- it tasted like the most expensive thing!", restaurant_id: 6, username: "Anonymous", dateposted: "03/22/2012", rating: 2)
rev7 = Review.create(review:"nice food, mediocre service, but this is america mirite", restaurant_id: 7, username: "Brandon_teacherman", dateposted: "02/19/2004", rating: 1)
rev8 = Review.create(review:"everythings great, I enjoyed bringing my mistress here! Don't tell my wife ;)", restaurant_id: 8, username: "Anonymous", dateposted: "07/30/2003", rating: 5)
rev9 = Review.create(review:"bombdiggity- and I mean it. They didn't even care that I was eating off the floor!", restaurant_id: 9, username: "Flatiron_School", dateposted: "08/20/2012", rating: 4)
rev10 = Review.create(review:"yum yum in my tum tum, yum yum yum", restaurant_id: 10, username: "dave", dateposted: "06/21/2013", rating: 2)

rev11 = Review.create(review:"I loved it- would have gave them a five star rating if it wasn't for the long curly hair I found in my food!", restaurant_id: 1, username: "Willy_Blanco", dateposted: "04/20/2021", rating: 4)
rev12 = Review.create(review:"We are super picky and have extravagent tastebuds, this was so mid, no sirry, not for us.", restaurant_id: 2, username: "AxelandMatt", dateposted: "03/12/2014", rating: 2)
rev13 = Review.create(review:"damn that was gross. Even their water tastes weird", restaurant_id: 3, username: "ZelieBellie", dateposted: "02/09/2013", rating: 1)
rev14 = Review.create(review:"mid", restaurant_id: 4, username: "Anonymous", dateposted: "01/10/2012", rating: 4)
rev15 = Review.create(review:"Brought my cousin here, she said she had the best dinner of her life, so for that, here's a 5 star rating!", restaurant_id: 5, username: "Anonymous", dateposted: "04/08/2022", rating: 5)
rev16 = Review.create(review:"Too far from my house, food not up to par, and i'm not even in a bad mood right now so that's how you know this place really sucks. sorry- not sorry.", restaurant_id: 6, username: "Bridget_duh", dateposted: "10/04/2021", rating: 2)
rev17 = Review.create(review:"I have a reputation to uphold, so I won't unleash the wrath of a thousand fireballs right now- just know it's not good.", restaurant_id: 7, username: "Brandon_teacherman", dateposted: "06/20/2017", rating: 1)
rev18 = Review.create(review:"Polite staff, clean bathrooms, and excellent food. 10/10 for me!", restaurant_id: 8, username: "Anonymous", dateposted: "01/16/2015", rating: 5)
rev19 = Review.create(review:"I mean, it's not the worst thing I've ever put in my mouth.", restaurant_id: 9, username: "Flatiron_School", dateposted: "07/12/2019", rating: 2)
rev20 = Review.create(review:"No- just No.", restaurant_id: 10, username: "dave", dateposted: "02/24/2015", rating: 1)

rev21 = Review.create(review:"its alright, I wouldn't come back unless it was just super convenient or something.", restaurant_id: 1, username: "Jake_the_man", dateposted: "01/20/2020", rating: 4)
rev22 = Review.create(review:"I loved it- would have gave them a five star rating if it wasn't for the long curly hair I found in my food!", restaurant_id: 2, username: "ZelieBellie", dateposted: "12/24/2016", rating: 4)
rev23 = Review.create(review:"I'm super picky and have extravagent tastebuds, this was so mid, no sirry, not for me.", restaurant_id: 3, username: "SamTheMan", dateposted: "09/02/2012", rating: 3)
rev24 = Review.create(review:"damn that was gross. Even their water tastes weird", restaurant_id: 4, username: "Anonymous", dateposted: "04/24/2012", rating: 2)
rev25 = Review.create(review:"Brought my cousin here, she said she had the best dinner of her life, so for that, here's a 5 star rating!", restaurant_id: 5, username: "Anonymous", dateposted: "05/23/2016", rating: 5)
rev26 = Review.create(review:"I mean, it's not the worst thing I've ever put in my mouth.", restaurant_id: 6, username: "Willy_Blanco", dateposted: "11/25/2021", rating: 2)
rev27 = Review.create(review:"You put an egg in my Cola... but I also had the best lunch i've had in months here.. don't really know how to feel about you guys right now.", restaurant_id: 7, username: "Anonymous", dateposted: "04/28/2021", rating: 3)
rev28 = Review.create(review:"Talk about a location where you can feel the great energy in the air! Lovely people too!", restaurant_id: 8, username: "Flatiron_School", dateposted: "09/24/2013", rating: 5)
rev29 = Review.create(review:"We ordered catering for our students, no one ate it and now we have a raccoon problem. We blame you. Thanks a lot.", restaurant_id: 9, username: "dave", dateposted: "03/09/2020", rating: 2)
rev30 = Review.create(review:"Anyone who likes this place is crazy. I mean it.", restaurant_id: 10, username: "Brandon_teacherman", dateposted: "07/11/2009", rating: 1)

puts "🏕 Seeding items..."
i1 = Item.create(name: 'Gringo Taco', price:5.00, restaurant_id:1, description: Faker::Food.description)
i2 = Item.create(name: 'Shrimp Bowl', price:14.00, restaurant_id:1, description: Faker::Food.description)
i3 = Item.create(name: 'Pollo Asado Quesadilla', price:13.00, restaurant_id:1, description: Faker::Food.description)
i4 = Item.create(name: 'Polllo Asado Burrito', price:13.00, restaurant_id:1, description: Faker::Food.description)
i5 = Item.create(name: 'Chile Cilantro Fries', price:7.00, restaurant_id:1, description: Faker::Food.description)
i6 = Item.create(name: 'Chips and Guacamole', price:14.00, restaurant_id:1, description: Faker::Food.description)
i7 = Item.create(name: 'Crispy Brussel Sprouts', price:10.00, restaurant_id:1, description: Faker::Food.description)
i8 = Item.create(name: 'Crispy Rolled Tacos (Chicken and Bacon)', price:12.00, restaurant_id:1, description: Faker::Food.description)
i9 = Item.create(name: 'Jarritos', price:4.00, restaurant_id:1, description: Faker::Food.description)
i10 = Item.create(name: 'Mexican Coke', price:4.00, restaurant_id:1, description: Faker::Food.description)
i11= Item.create(name: 'Water', price:2.00, restaurant_id:1, description: Faker::Food.description)
i12= Item.create(name: 'Chic-Fil-A Chicken Sandwich Meal', price:7.79, restaurant_id:2, description: Faker::Food.description)
i13= Item.create(name: 'Spicy Chicken Deluxe Meal', price:8.09, restaurant_id:2, description: Faker::Food.description)
i14= Item.create(name: 'Chic-Fil-A Nuggets Meal 8ct', price:7.19, restaurant_id:2, description: Faker::Food.description)
i15= Item.create(name: 'Chick-n-Strips 3ct Meal', price:7.59, restaurant_id:2, description: Faker::Food.description)
i16= Item.create(name: 'Grilled Chicken Sandwich Meal', price:8.69, restaurant_id:2, description: Faker::Food.description)
i17= Item.create(name: 'Grilled Nuggets Meal', price:7.95, restaurant_id:2, description: Faker::Food.description)
i18= Item.create(name: 'Chicken Bowl/Burrito', price:6.50, restaurant_id:3, description: Faker::Food.description)
i19= Item.create(name: 'Steak Bowl/Burrito', price:7.50, restaurant_id:3, description: Faker::Food.description)
i20= Item.create(name: 'Carnitas Bowl/Burrito',price:6.95, restaurant_id:3, description: Faker::Food.description)
i21= Item.create(name: 'Salad (Vegitarian)', price:6.50, restaurant_id:3, description: Faker::Food.description)
i22= Item.create(name: 'Taco (Barbacoa) 3 pc.', price:6.50, restaurant_id:3, description: Faker::Food.description)
i23= Item.create(name: 'Soda Regular', price:1.80, restaurant_id:3, description: Faker::Food.description)
i24= Item.create(name: 'Soda Large', price:2.10, restaurant_id:3, description: Faker::Food.description)
i25= Item.create(name: 'Santa Fe', price:8.50, restaurant_id:4, description: Faker::Food.description)
i26= Item.create(name: 'Mexican Caesar', price:6.99, restaurant_id:4, description: Faker::Food.description)
i27= Item.create(name: 'Kebab Cobb', price:9.50, restaurant_id:4, description: Faker::Food.description)
i28= Item.create(name: 'Crispy Chicken Ranch', price:9.50, restaurant_id:4, description: Faker::Food.description)
i29= Item.create(name: 'Kale Caesar', price:6.99, restaurant_id:4, description: Faker::Food.description)
i30= Item.create(name: 'Palm Beach', price:9.99, restaurant_id:4, description: Faker::Food.description)
i31= Item.create(name: 'Asparagus Kale Caesar', price:9.75, restaurant_id:5, description: Faker::Food.description)
i32= Item.create(name: 'Chicken & the Egg', price:10.25, restaurant_id:5, description: Faker::Food.description)
i33= Item.create(name: 'Spring Harvest', price:9.75, restaurant_id:5, description: Faker::Food.description)
i34= Item.create(name: 'Classic Dig', price:10.25, restaurant_id:5, description: Faker::Food.description)
i35= Item.create(name: 'Steak and Spring Vegitables', price:12.25, restaurant_id:5, description: Faker::Food.description)
i36= Item.create(name: 'Coconut Water', price:2.99, restaurant_id:5, description: Faker::Food.description)
i37= Item.create(name: 'Ginger Mint Lemonade', price:2.99, restaurant_id:5, description: Faker::Food.description)
i38= Item.create(name: 'Big Mac Meal', price:7.70, restaurant_id:6, description: Faker::Food.description)
i39= Item.create(name: 'Quarter Pounder With Cheese Meal', price:7.30, restaurant_id:6, description: Faker::Food.description)
i40= Item.create(name: 'Crispy Chicken Sandwich Meal', price:6.90, restaurant_id:6, description: Faker::Food.description)
i41= Item.create(name: '10 Pc McNuggets Meal', price:7.40, restaurant_id:6, description: Faker::Food.description)
i42= Item.create(name: 'M&M McFlurry', price:3.75, restaurant_id:6, description: Faker::Food.description)
i42= Item.create(name: 'Hot Fudge Sundae', price:3.00, restaurant_id:6, description: Faker::Food.description)
i43= Item.create(name: 'Beef Shawarma Roll', price:8.00, restaurant_id:7, description: Faker::Food.description)
i44= Item.create(name: 'Beef Kebab', price:8.27, restaurant_id:7, description: Faker::Food.description)
i45= Item.create(name: 'Chicken Shawarma Roll', price:8.00, restaurant_id:7, description: Faker::Food.description)
i46= Item.create(name: 'Falafel Roll', price:6.88, restaurant_id:7, description: Faker::Food.description)
i47= Item.create(name: 'Chicken Shawarma Bowl', price:8.75, restaurant_id:7, description: Faker::Food.description)
i48= Item.create(name: 'Kafta Lamb Kebab Bowl', price:8.03, restaurant_id:7, description: Faker::Food.description)
i49= Item.create(name: 'Snack Poke Bowl', price:9.95, restaurant_id:8, description: Faker::Food.description)
i50= Item.create(name: 'Plenty Poke Bowl', price:13.45, restaurant_id:8, description: Faker::Food.description)
i51= Item.create(name: 'To The Max Poke Bowl', price:15.95, restaurant_id:8, description: Faker::Food.description)
i52= Item.create(name: 'Create Your Own Poke Burrito', price:11.95, restaurant_id:8, description: Faker::Food.description)
i53= Item.create(name: 'Poke Bowl Plenty Special', price:14.95, restaurant_id:8, description: Faker::Food.description)
i54= Item.create(name: 'Poke Bowl House Pineapple Soda', price:2.45, restaurant_id:8, description: Faker::Food.description)
i55= Item.create(name: 'Chicken Chimichurri', price:10.45, restaurant_id:9, description: Faker::Food.description)
i56= Item.create(name: 'Mushroom Chimichurri', price:9.45, restaurant_id:9, description: Faker::Food.description)
i57= Item.create(name: 'Shroomami', price:10.25, restaurant_id:9, description: Faker::Food.description)
i58= Item.create(name: 'Harvest Bowl', price:11.25, restaurant_id:9, description: Faker::Food.description)
i59= Item.create(name: 'Fish Taco Bowl', price:12.25, restaurant_id:9, description: Faker::Food.description)
i60= Item.create(name: 'Crispy Rice Bowl', price:10.75, restaurant_id:9, description: Faker::Food.description)
i61= Item.create(name: 'Daves Hot n Juicy 1/4 Single with Cheese Combo', price:7.99, restaurant_id:10, description: Faker::Food.description)
i62= Item.create(name: 'Baconator Combo', price:9.89, restaurant_id:10, description: Faker::Food.description)
i63= Item.create(name: 'Son Of Baconator Combo', price:7.99, restaurant_id:10, description: Faker::Food.description)
i64= Item.create(name: '10 pc Nugget Combo', price:7.19, restaurant_id:10, description: Faker::Food.description)
i65= Item.create(name: 'Spicy Chicken Sandwich Combo', price:8.59, restaurant_id:10, description: Faker::Food.description)
i65= Item.create(name: 'Frosty', price:3.99, restaurant_id:10, description: Faker::Food.description)


puts "🏕 Seeding restaurants..."
r1 = Restaurant.create(image_url:'/calexico.jpg', title: 'Calexico', distance: 35, delivery_fee: 4.50, items: [i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11], reviews: [rev1, rev11, rev21])
r2 = Restaurant.create(image_url:'/chic.png', title: 'Chic-Fil-A', distance: 20, delivery_fee: 2.00, items: [i12, i13, i14, i15, i16, i17, i18, i19, i20, i21, i22], reviews: [rev2, rev12, rev22])
r3 = Restaurant.create(image_url:'/chipotle.svg.png', title: 'Chipotle', distance: 30, delivery_fee: 2.50, items: [i23, i23, i25, i26, i27], reviews: [rev3, rev13, rev23])
r4 = Restaurant.create(image_url:'/chopt.jpg', title: 'Chopt', distance: 15, delivery_fee: 5.00, items: [i33, i34, i35, i36, i37, i38, i39], reviews: [rev4, rev14, rev24])
r5 = Restaurant.create(image_url:'/dig.webp', title: 'Dig', distance: 45, delivery_fee: 3.00, items: [i44, i45, i46, i47, i48, i49], reviews: [rev5, rev15, rev25])
r6 = Restaurant.create(image_url:'/mcdonald.jpg', title: 'Mcdonalds', distance: 15, delivery_fee: 3.50, items: [i50, i51, i52, i53, i54], reviews: [rev6, rev16, rev26])
r7 = Restaurant.create(image_url:'naya.png', title: 'Naya Express',  distance: 25, delivery_fee: 4.00, items: [i55, i56, i57, i58, i59, i60], reviews: [rev7, rev17, rev27])
r8 = Restaurant.create(image_url:'/poke.jpg', title: 'Poke Bowl', distance: 20, delivery_fee: 2.00, items: [i40, i41, i42, i43], reviews: [rev8, rev18, rev28])
r9 = Restaurant.create(image_url:'/sweetgreen.png', title: 'Sweetgreen', distance: 30, delivery_fee: 3.50, items: [i61, i62, i63, i64, i65], reviews: [rev9, rev19, rev29])
r10 = Restaurant.create( image_url:'/wendy.svg.png', title: 'Wendys', distance: 15, delivery_fee: 8.50, items: [i28, i29, i30, i31, i32], reviews: [rev10, rev20, rev30])


