Item.destroy_all
Restaurant.destroy_all
Review.destroy_all 

puts "seeding reviews"

rev1 = Review.create(review:"its good", restaurant_id: 1)
rev2 = Review.create(review:"its ok", restaurant_id: 2)
rev3 = Review.create(review:"its bad", restaurant_id: 3)
rev4 = Review.create(review:"its alright", restaurant_id: 4)
rev5 = Review.create(review:"its the best", restaurant_id: 5)
rev6 = Review.create(review:"its bomb", restaurant_id: 6)
rev7 = Review.create(review:"nice food", restaurant_id: 7)
rev8 = Review.create(review:"everythings great", restaurant_id: 8)
rev9 = Review.create(review:"bombdiggity", restaurant_id: 9)
rev10 = Review.create(review:"yum yum in my tum tum", restaurant_id: 10)


puts "🏕 Seeding items..."
i1 = Item.create(name: 'Gringo Taco', price:5.00, restaurant_id:1)
i2 = Item.create(name: 'Shrimp Bowl', price:14.00, restaurant_id:1)
i3 = Item.create(name: 'Pollo Asado Quesadilla', price:13.00, restaurant_id:1)
i4 = Item.create(name: 'Polllo Asado Burrito', price:13.00, restaurant_id:1)
i5 = Item.create(name: 'Chile Cilantro Fries', price:7.00, restaurant_id:1)
i6 = Item.create(name: 'Chips and Guacamole', price:14.00, restaurant_id:1)
i7 = Item.create(name: 'Crispy Brussel Sprouts', price:10.00, restaurant_id:1)
i8 = Item.create(name: 'Crispy Rolled Tacos (Chicken and Bacon)', price:12.00, restaurant_id:1)
i9 = Item.create(name: 'Jarritos', price:4.00, restaurant_id:1)
i10 = Item.create(name: 'Mexican Coke', price:4.00, restaurant_id:1)
i11= Item.create(name: 'Water', price:2.00, restaurant_id:1)
i12= Item.create(name: 'Chic-Fil-A Chicken Sandwich Meal', price:7.79, restaurant_id:2)
i13= Item.create(name: 'Spicy Chicken Deluxe Meal', price:8.09, restaurant_id:2)
i14= Item.create(name: 'Chic-Fil-A Nuggets Meal 8ct', price:7.19, restaurant_id:2)
i15= Item.create(name: 'Chick-n-Strips 3ct Meal', price:7.59, restaurant_id:2)
i16= Item.create(name: 'Grilled Chicken Sandwich Meal', price:8.69, restaurant_id:2)
i17= Item.create(name: 'Grilled Nuggets Meal', price:7.95, restaurant_id:2)
i18= Item.create(name: 'Chicken Bowl/Burrito', price:6.50, restaurant_id:3)
i19= Item.create(name: 'Steak Bowl/Burrito', price:7.50, restaurant_id:3)
i20= Item.create(name: 'Carnitas Bowl/Burrito',price:6.95, restaurant_id:3)
i21= Item.create(name: 'Salad (Vegitarian)', price:6.50, restaurant_id:3)
i22= Item.create(name: 'Taco (Barbacoa) 3 pc.', price:6.50, restaurant_id:3)
i23= Item.create(name: 'Soda Regular', price:1.80, restaurant_id:3)
i24= Item.create(name: 'Soda Large', price:2.10, restaurant_id:3)
i25= Item.create(name: 'Santa Fe', price:8.50, restaurant_id:4)
i26= Item.create(name: 'Mexican Caesar', price:6.99, restaurant_id:4)
i27= Item.create(name: 'Kebab Cobb', price:9.50, restaurant_id:4)
i28= Item.create(name: 'Crispy Chicken Ranch', price:9.50, restaurant_id:4)
i29= Item.create(name: 'Kale Caesar', price:6.99, restaurant_id:4)
i30= Item.create(name: 'Palm Beach', price:9.99, restaurant_id:4)
i31= Item.create(name: 'Asparagus Kale Caesar', price:9.75, restaurant_id:5)
i32= Item.create(name: 'Chicken & the Egg', price:10.25, restaurant_id:5)
i33= Item.create(name: 'Spring Harvest', price:9.75, restaurant_id:5)
i34= Item.create(name: 'Classic Dig', price:10.25, restaurant_id:5)
i35= Item.create(name: 'Steak and Spring Vegitables', price:12.25, restaurant_id:5)
i36= Item.create(name: 'Coconut Water', price:2.99, restaurant_id:5)
i37= Item.create(name: 'Ginger Mint Lemonade', price:2.99, restaurant_id:5)
i38= Item.create(name: 'Big Mac Meal', price:7.70, restaurant_id:6)
i39= Item.create(name: 'Quarter Pounder With Cheese Meal', price:7.30, restaurant_id:6)
i40= Item.create(name: 'Crispy Chicken Sandwich Meal', price:6.90, restaurant_id:6)
i41= Item.create(name: '10 Pc McNuggets Meal', price:7.40, restaurant_id:6)
i42= Item.create(name: 'M&M McFlurry', price:3.75, restaurant_id:6)
i42= Item.create(name: 'Hot Fudge Sundae', price:3.00, restaurant_id:6)
i43= Item.create(name: 'Beef Shawarma Roll', price:8.00, restaurant_id:7)
i44= Item.create(name: 'Beef Kebab', price:8.27, restaurant_id:7)
i45= Item.create(name: 'Chicken Shawarma Roll', price:8.00, restaurant_id:7)
i46= Item.create(name: 'Falafel Roll', price:6.88, restaurant_id:7)
i47= Item.create(name: 'Chicken Shawarma Bowl', price:8.75, restaurant_id:7)
i48= Item.create(name: 'Kafta Lamb Kebab Bowl', price:8.03, restaurant_id:7)
i49= Item.create(name: 'Snack Poke Bowl', price:9.95, restaurant_id:8)
i50= Item.create(name: 'Plenty Poke Bowl', price:13.45, restaurant_id:8)
i51= Item.create(name: 'To The Max Poke Bowl', price:15.95, restaurant_id:8)
i52= Item.create(name: 'Create Your Own Poke Burrito', price:11.95, restaurant_id:8)
i53= Item.create(name: 'Poke Bowl Plenty Special', price:14.95, restaurant_id:8)
i54= Item.create(name: 'Poke Bowl House Pineapple Soda', price:2.45, restaurant_id:8)
i55= Item.create(name: 'Chicken Chimichurri', price:10.45, restaurant_id:9)
i56= Item.create(name: 'Mushroom Chimichurri', price:9.45, restaurant_id:9)
i57= Item.create(name: 'Shroomami', price:10.25, restaurant_id:9)
i58= Item.create(name: 'Harvest Bowl', price:11.25, restaurant_id:9)
i59= Item.create(name: 'Fish Taco Bowl', price:12.25, restaurant_id:9)
i60= Item.create(name: 'Crispy Rice Bowl', price:10.75, restaurant_id:9)
i61= Item.create(name: 'Daves Hot n Juicy 1/4 Single with Cheese Combo', price:7.99, restaurant_id:10)
i62= Item.create(name: 'Baconator Combo', price:9.89, restaurant_id:10)
i63= Item.create(name: 'Son Of Baconator Combo', price:7.99, restaurant_id:10)
i64= Item.create(name: '10 pc Nugget Combo', price:7.19, restaurant_id:10)
i65= Item.create(name: 'Spicy Chicken Sandwich Combo', price:8.59, restaurant_id:10)
i65= Item.create(name: 'Frosty', price:3.99, restaurant_id:10)


puts "🏕 Seeding restaurants..."
r1 = Restaurant.create(image_url:'/calexico.jpg', name: 'Calexico', distance: 35, delivery_fee: 4.50, items: [i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11], reviews: [rev1])
r2 = Restaurant.create(image_url:'/chic.png', name: 'Chic-Fil-A', distance: 20, delivery_fee: 2.00, items: [i12, i13, i14, i15, i16, i17, i18, i19, i20, i21, i22], reviews: [rev2])
r3 = Restaurant.create(image_url:'/chipotle.svg.png', name: 'Chipotle', distance: 30, delivery_fee: 2.50, items: [i23, i23, i25, i26, i27], reviews: [rev3])
r4 = Restaurant.create(image_url:'/chopt.jpg', name: 'Chopt', distance: 15, delivery_fee: 5.00, items: [i33, i34, i35, i36, i37, i38, i39], reviews: [rev4])
r5 = Restaurant.create(image_url:'/dig.webp', name: 'Dig', distance: 45, delivery_fee: 3.00, items: [i44, i45, i46, i47, i48, i49], reviews: [rev5])
r6 = Restaurant.create(image_url:'/mcdonald.jpg', name: 'Mcdonalds', distance: 15, delivery_fee: 3.50, items: [i50, i51, i52, i53, i54], reviews: [rev6])
r7 = Restaurant.create(image_url:'naya.png', name: 'Naya Express',  distance: 25, delivery_fee: 4.00, items: [i55, i56, i57, i58, i59, i60], reviews: [rev7])
r8 = Restaurant.create(image_url:'/poke.jpg', name: 'Poke Bowl', distance: 20, delivery_fee: 2.00, items: [i40, i41, i42, i43], reviews: [rev8])
r9 = Restaurant.create(image_url:'/sweetgreen.png', name: 'Sweetgreen', distance: 30, delivery_fee: 3.50, items: [i61, i62, i63, i64, i65], reviews: [rev9])
r10 = Restaurant.create( image_url:'/wendy.svg.png',name: 'Wendys', distance: 15, delivery_fee: 8.50, items: [i28, i29, i30, i31, i32], reviews: [rev10])


